CREATE DATABASE project3;
USE project3;
CREATE TABLE sales (
    OrderID VARCHAR(20),
    Date DATE,
    CustomerID VARCHAR(20),
    Product VARCHAR(50),
    Quantity INT,
    UnitPrice DECIMAL(10,2),
    ShippingAddress VARCHAR(255),
    PaymentMethod VARCHAR(50),
    OrderStatus VARCHAR(50),
    TrackingNumber VARCHAR(50),
    ItemsInCart INT,
    CouponCode VARCHAR(50),
    ReferralSource VARCHAR(50),
    TotalPrice DECIMAL(10,2)
);  

#View all records
SELECT *
FROM sales;

#Display Product and TotalPrice
SELECT Product, TotalPrice
FROM sales;

#Orders with TotalPrice greater than 1000
SELECT *
FROM sales
WHERE TotalPrice > 1000;

#Orders sorted by TotalPrice
SELECT *
FROM sales
ORDER BY TotalPrice DESC;

#Count total orders
SELECT COUNT(*) AS TotalOrders
FROM sales;

#Calculate total revenue
SELECT SUM(TotalPrice) AS TotalRevenue
FROM sales;

#Average order value
SELECT AVG(TotalPrice) AS AverageOrderValue
FROM sales;

#Revenue generated by each product
SELECT Product,
       SUM(TotalPrice) AS Revenue
FROM sales
GROUP BY Product
ORDER BY Revenue DESC;

#Number of orders for each product
SELECT Product,
       COUNT(*) AS OrderCount
FROM sales
GROUP BY Product
ORDER BY OrderCount DESC;

#Revenue by payment method
SELECT PaymentMethod,
       SUM(TotalPrice) AS Revenue
FROM sales
GROUP BY PaymentMethod
ORDER BY Revenue DESC;

#Revenue by referral source
SELECT ReferralSource,
       SUM(TotalPrice) AS Revenue
FROM sales
GROUP BY ReferralSource
ORDER BY Revenue DESC;

#Orders by status
SELECT OrderStatus,
       COUNT(*) AS TotalOrders
FROM sales
GROUP BY OrderStatus;


# Revenue by order status
SELECT OrderStatus,
       SUM(TotalPrice) AS Revenue
FROM sales
GROUP BY OrderStatus
ORDER BY Revenue DESC;


# Top 5 highest revenue products
SELECT Product,
       SUM(TotalPrice) AS Revenue
FROM sales
GROUP BY Product
ORDER BY Revenue DESC
LIMIT 5;


#Average revenue by product
SELECT Product,
       AVG(TotalPrice) AS AverageRevenue
FROM sales
GROUP BY Product
ORDER BY AverageRevenue DESC;


#Revenue by year
SELECT YEAR(Date) AS SalesYear,
       SUM(TotalPrice) AS Revenue
FROM sales
GROUP BY YEAR(Date)
ORDER BY SalesYear;


#Orders using coupon codes
SELECT CouponCode,
       COUNT(*) AS TotalOrders
FROM sales
GROUP BY CouponCode;


#Highest value order
SELECT *
FROM sales
ORDER BY TotalPrice DESC
LIMIT 1;


#Total revenue from Instagram
SELECT SUM(TotalPrice) AS InstagramRevenue
FROM sales
WHERE ReferralSource = 'Instagram';


#Delivered orders only
SELECT *
FROM sales
WHERE OrderStatus = 'Delivered';